export const ADD_ORDER = "ADD_ORDER";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const ORDERS_FETCHED = "ORDERS_FETCHED";
export const SERVER_ERROR = "SERVER_ERROR";
export const ITEMS_FETCHED = "ITEMS_FETCHED";

// CREATE ORDER
export const CREATE_ORDER = "CREATE_ORDER";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR";

export const RESET_CREATED_ORDER_ID = "RESET_CREATED_ORDER_ID";

// UPDATE ORDER
export const UPDATE_ORDER = "UPDATE_ORDER";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_ERROR = "UPDATE_ORDER_ERROR";

// FETCH ITEMS IN ORDER
export const FETCH_ORDER_ITEMS = "FETCH_ORDER_ITEMS";
export const FETCH_ORDER_ITEMS_SUCCESS = "FETCH_ORDER_ITEMS_SUCCESS";
export const FETCH_ORDER_ITEMS_ERROR = "FETCH_ORDER_ITEMS_ERROR";

// DELETE ITEM FROM ORDER
export const REMOVE_ORDER_ITEM = "REMOVE_ORDER_ITEM";
export const REMOVE_ORDER_ITEM_SUCCESS = "REMOVE_ORDER_ITEM_SUCCESS";
export const REMOVE_ORDER_ITEM_ERROR = "REMOVE_ORDER_ITEM_ERROR";

export const SET_ITEM_QUANTITY = "SET_ITEM_QUANTITY";
export const ADD_ORDER_ITEMS = "ADD_ORDER_ITEMS";