export const ADD_ORDER = "ADD_ORDER";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const ORDERS_FETCHED = "ORDERS_FETCHED";
export const SERVER_ERROR = "SERVER_ERROR";
export const ITEMS_FETCHED = "ITEMS_FETCHED";

export const CREATE_ORDER = "CREATE_ORDER";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR";

export const RESET_CREATED_ORDER_ID = "RESET_CREATED_ORDER_ID";